# -*- coding: utf-8 -*-
"""validar número

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFwq5C9d5zT6HjQN-ZVIihjxPfVLIS9w
"""

import re

def validar_numero(numero):
  padrao = re.compile(r"\(\d{2}\) 9\d{4}-\d{4}")
  if padrao.match(numero):
    return "Número de telefone válido."
  else:
    return "Número de telefone inválido."

phone_number = input()


print(validar_numero(phone_number))